name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  cloud_firestore: ^4.9.0
  either_dart: ^0.3.0
  shared_preferences: ^2.0.6
  firebase_storage: ^11.2.6
  models_repository: 
    path: ../models_repository
