name: data_repository
description: Dart package which manages data throughout the app which includes, feed posts content and so on.
publish_to: none

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  models_repository: 
    path: ../models_repository
